### ISSUE TITLE
Move to gh-pages branch?

### ISSUE THREAD

**Issue by pkra** [mathjax/papers#1]
Should we delete master and make gh-pages the default? That will drop the need to keep them in sync.

**Comment by christianp** [comment]
You can always make a new branch in the future if you want to do something that doesn't go online.

**Comment by pkra** [comment]
Indeed.

**Comment by zorkow** [comment]
sgtm.

**Comment by pkra** [comment]
Done.

**Comment by pkra** [comment]
Note:  please delete local master branches to prevent accidentally pushing new branches.
